#!/bin/bash
# Cross-compile the demo binary for the BeagleBone in a Docker container.
# A full parallel build takes well under a minute on a desktop, so this is
# the fast path for development; compile.sh on the BeagleBone remains the
# reference build.
#
# The PRU firmware (10.01_base/4_deploy_<suffix>/*_array.c and *.out) is
# generated by the TI clpru compiler, which runs in its own container here, so
# a build needs nothing but this repository and Docker. See PRU_CGT_VERSION
# below for what pins the compiler.
#
# usage:
#   ./crossbuild.sh            build for QBUS (demo binary)
#   ./crossbuild.sh -u         build for UNIBUS
#   ./crossbuild.sh -d         build and deploy the binary to $QUNILATOR_HOST
#   ./crossbuild.sh -c         clean object directory first
#   ./crossbuild.sh -p         rebuild the PRU firmware even if it is present
#
# Both PRU firmwares are built: the one that drives a backplane and the one that
# keeps the bus inside the PRU. The emulator carries both and loads whichever the
# board's bus-mode setting names, so one binary serves either use.
#
# environment:
#   QUNILATOR_HOST   ssh destination of the device (default hans@qbone.huebner.org)
#   QUNILATOR_REMOTE_DIR  checkout directory on the device (default ~/QUniLator)

set -e
cd "$(dirname "$0")"

QUNILATOR_HOST=${QUNILATOR_HOST:-hans@qbone.huebner.org}
QUNILATOR_REMOTE_DIR=${QUNILATOR_REMOTE_DIR:-QUniLator}
IMAGE=qunibone-crossbuild
PRU_IMAGE=qunibone-pru-cgt

# The PRU code generation tools, pinned to the version that built the firmware
# the emulator has been verified with. clpru's output is what the bus state
# machine's cycle timing depends on, so the compiler is part of the product and
# moving to a newer one is a change to be measured, not a version bump.
PRU_CGT_VERSION=2.3.1

# Build containers write into the mounted tree as this user, so the generated
# firmware and objects are owned by the caller rather than by root. Docker
# Desktop maps bind-mount ownership to the host user on its own; a Linux host
# (a CI runner) does not, and a root-owned tree then breaks the touch and the
# header-stamp write that follow the build.
DOCKER_USER="$(id -u):$(id -g)"

SUFFIX=_q
PLATFORM=QBUS
DEPLOY=0
CLEAN=0
PRU_CLEAN=0
while getopts "udcp" opt; do
    case $opt in
        u) SUFFIX=_u; PLATFORM=UNIBUS;;
        d) DEPLOY=1;;
        c) CLEAN=1;;
        p) PRU_CLEAN=1;;
        *) exit 1;;
    esac
done

# builder image: Debian with the armhf cross toolchain.
#
# The tag carries a hash of the recipe, so editing anything below builds a new
# image instead of reusing one that no longer matches what it says.
CROSSBUILD_RECIPE=$(cat <<'EOF'
# Trixie, the distribution the appliance image carries: the emulator links
# against its shared libraries, so builder and board agree on their versions.
FROM debian:trixie-slim
# armhf as a foreign architecture: the target's libraries are linked into the
# emulator, not run on the builder
RUN dpkg --add-architecture armhf && apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf make file \
        curl ca-certificates bzip2 \
        libx11-dev:armhf libxcb1-dev:armhf libxau-dev:armhf libxdmcp-dev:armhf \
    && rm -rf /var/lib/apt/lists/*
# Sun RPC for the blinkenlight API client: modern glibc no longer bundles it;
# libtirpc replaces it, built without GSSAPI so it links statically
RUN curl -sL https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.4.tar.bz2 | tar xj -C /tmp \
    && cd /tmp/libtirpc-1.3.4 \
    && ./configure --host=arm-linux-gnueabihf --disable-gssapi --disable-shared \
        --prefix=/usr/local/tirpc-armhf \
    && make -j"$(nproc)" && make install \
    && rm -rf /tmp/libtirpc-1.3.4
EOF
)
IMAGE=$IMAGE:$(printf '%s' "$CROSSBUILD_RECIPE" | shasum | cut -c1-12)

if ! docker image inspect $IMAGE >/dev/null 2>&1; then
    echo "Building $IMAGE docker image ..."
    printf '%s\n' "$CROSSBUILD_RECIPE" | docker build -t $IMAGE -
fi

# builder image: the TI PRU code generation tools. clpru is an x86-64 binary
# and its installer is i386, so this image is amd64 whatever the host is, and
# carries the 32-bit C library the installer needs to unpack itself.
if [ $PRU_CLEAN = 1 ] || ! docker image inspect $PRU_IMAGE >/dev/null 2>&1; then
    echo "Building $PRU_IMAGE docker image ..."
    docker build --platform linux/amd64 -t $PRU_IMAGE \
        --build-arg CGT_VERSION=$PRU_CGT_VERSION - <<'EOF'
FROM --platform=linux/amd64 debian:bookworm-slim
ARG CGT_VERSION
RUN dpkg --add-architecture i386 && apt-get update \
    && apt-get install -y --no-install-recommends make curl ca-certificates libc6:i386 \
    && curl -sLo /tmp/cgt.bin \
        "https://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/${CGT_VERSION}/ti_cgt_pru_${CGT_VERSION}_linux_installer_x86.bin" \
    && chmod +x /tmp/cgt.bin \
    && /tmp/cgt.bin --prefix /opt/ti --mode unattended \
    && rm /tmp/cgt.bin && rm -rf /var/lib/apt/lists/*
ENV PRU_CGT=/opt/ti/ti-cgt-pru_${CGT_VERSION}
EOF
fi

# PRU firmware. Both forms are needed - instruction words for the prussdrv
# backend, the ELF itself for remoteproc - and both come out of the same build.
PRU_DEPLOY_DIR=10.01_base/4_deploy$SUFFIX
if [ $PRU_CLEAN = 1 ]; then
    rm -f "$PRU_DEPLOY_DIR"/*.out "$PRU_DEPLOY_DIR"/*_array.c \
          "$PRU_DEPLOY_DIR"/*.object "$PRU_DEPLOY_DIR"/*.pp \
          "$PRU_DEPLOY_DIR"/*.asm "$PRU_DEPLOY_DIR"/*.map "$PRU_DEPLOY_DIR"/*.nfo
fi
if [ -z "$(ls "$PRU_DEPLOY_DIR"/*_array.c 2>/dev/null || true)" ] \
        || [ -z "$(ls "$PRU_DEPLOY_DIR"/*.out 2>/dev/null || true)" ]; then
    echo "Building PRU firmware with clpru $PRU_CGT_VERSION ..."
    for prudir in pru0 pru1${SUFFIX}; do
        docker run --rm --platform linux/amd64 --user "$DOCKER_USER" \
            -v "$PWD:/qunibone" \
            -w "/qunibone/10.01_base/2_src/$prudir" $PRU_IMAGE \
            make QUNILATOR_DIR=/qunibone QUNILATOR_PLATFORM=$PLATFORM all
    done
fi
# The internal-bus PRU1 image: the same sources with NO_PHYSICAL_BUS, compiled
# into their own object directory because the switch reaches every object that
# touches a bus latch. Only the image and its ELF are lifted out; the objects
# stay behind so they never mix with the physical ones.
INT_NAME=$([ "$SUFFIX" = _u ] && echo unibusint || echo qbusint)
if [ ! -s "$PRU_DEPLOY_DIR/pru1_code_${INT_NAME}_array.c" ]; then
    echo "Building the internal-bus PRU firmware ..."
    docker run --rm --platform linux/amd64 --user "$DOCKER_USER" \
        -v "$PWD:/qunibone" \
        -w "/qunibone/10.01_base/2_src/pru1${SUFFIX}" $PRU_IMAGE \
        make QUNILATOR_DIR=/qunibone QUNILATOR_PLATFORM=$PLATFORM \
            OBJ_DIR="/qunibone/$PRU_DEPLOY_DIR/internal" \
            CC_CODE_FLAGS="-D$PLATFORM -DNO_PHYSICAL_BUS" internal
    cp "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}_array.c" \
       "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}_array.h" \
       "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}.out" "$PRU_DEPLOY_DIR/"
fi

# make must see them as newer than the PRU sources, or it tries to run clpru
touch "$PRU_DEPLOY_DIR"/*_array.c

OBJDIR="10.03_app_demo/4_deploy$SUFFIX"
HEADER_STAMP="$OBJDIR/.headers.sha"

# Adding or removing a virtual method, or changing a struct layout, in a
# shared header is an ABI change: incremental make relinks stale objects
# compiled against the old layout, and the mismatched vtables crash at
# runtime (a null-vtable jump). The makefile's header dependencies do not
# cover every object, so force a clean build whenever any header under
# 10.01_base/10.02_devices changed since the last build. A content hash is
# used, so re-touching a header without editing it does not trigger a clean.
header_hash() {
    find 10.01_base 10.02_devices -type f \( -name '*.h' -o -name '*.hpp' \) \
        -print0 | sort -z | xargs -0 cat 2>/dev/null | shasum | cut -d' ' -f1
}
HEADER_HASH=$(header_hash)
if [ $CLEAN = 0 ] && [ -f "$HEADER_STAMP" ] \
        && [ "$(cat "$HEADER_STAMP")" != "$HEADER_HASH" ]; then
    echo "Headers under 10.01_base/10.02_devices changed — forcing a clean build (ABI safety)."
    CLEAN=1
fi

if [ $CLEAN = 1 ]; then
    rm -rf "$OBJDIR"
fi

docker run --rm --user "$DOCKER_USER" -v "$PWD:/qunibone" \
    -w /qunibone/10.03_app_demo/2_src $IMAGE \
    make -f makefile$SUFFIX -j"$(sysctl -n hw.ncpu 2>/dev/null || echo 4)" \
        QUNILATOR_DIR=/qunibone \
        MAKE_CONFIGURATION=RELEASE \
        MAKE_TARGET_ARCH=BBB \
        BBB_CC=arm-linux-gnueabihf-gcc \
        CCDEFS=-I/usr/local/tirpc-armhf/include/tirpc \
        EXTRA_LIBS="-L/usr/local/tirpc-armhf/lib -ltirpc" \
        all

BINARY=$OBJDIR/demo
file "$BINARY"

# record the header state so the next incremental build detects ABI changes
# (the build recreated $OBJDIR); only reached on a successful build (set -e)
echo "$HEADER_HASH" > "$HEADER_STAMP"

if [ $DEPLOY = 1 ]; then
    echo "Deploying to $QUNILATOR_HOST:$QUNILATOR_REMOTE_DIR/$BINARY ..."
    # upload beside the binary, then rename: replaces it even while it runs
    scp "$BINARY" "$QUNILATOR_HOST:$QUNILATOR_REMOTE_DIR/$BINARY.new"
    ssh "$QUNILATOR_HOST" "mv '$QUNILATOR_REMOTE_DIR/$BINARY.new' '$QUNILATOR_REMOTE_DIR/$BINARY'"
fi
