#!/bin/bash
# Cross-compile the demo binary for the BeagleBone in a Docker container.
# A full parallel build takes well under a minute on a desktop, so this is
# the fast path for development; compile.sh on the BeagleBone remains the
# reference build.
#
# The PRU firmware (10.01_base/4_deploy_<suffix>/*_array.c and *.out) is
# generated by the TI clpru compiler, which runs in its own container here, so
# a build needs nothing but this repository and Docker. See PRU_CGT_VERSION
# below for what pins the compiler.
#
# "./crossbuild.sh -h" summarises the options; usage() below is what it prints,
# so that summary is the one place they are listed. Plain "./crossbuild.sh"
# builds for the bus build.env records, which is the board that is going to run
# the result; -u and -q build the other one for a run.
#
# "-g" builds the emulator unoptimised and with debug symbols, into an object
# directory of its own, so a debug and an optimised tree never share objects and
# switching between them costs no rebuild. It changes only the C++ emulator: the
# PRU firmware, whose timing is the product, is always built the one way.
#
# A UNIBUS build tests the emulated CPU cores before it builds the binary: the
# MAINDEC diagnostics of 10.06_cputest run with the host compiler in the same
# container, so a core defect stops the build (and any deploy) rather than
# reaching the board. Only the (core, tape) pairs whose sources changed are
# re-run, so an unrelated build pays nothing. A QBUS build does not run them -
# a QBone drives a real CPU board and has no emulated CPU.
#
# Both PRU firmwares are built: the one that drives a backplane and the one that
# keeps the bus inside the PRU. The emulator carries both and loads whichever the
# board's bus-mode setting names, so one binary serves either use.
#
# Where -d deploys to is described by build.env, which names one person's board
# and so is not in git. The first run copies build.env.example to it and stops
# so it can be filled in; build.env.example documents every setting.

set -e
cd "$(dirname "$0")"

# Deploy settings, read before the options so that -h can show what they
# currently say. What they have to contain is checked after the options are
# parsed, since asking for the summary is not a build and needs no board.
[ -f build.env ] && . ./build.env

# The example's placeholder host counts as no value: it is the one thing every
# copy of build.env carries and no board answers to.
if [ "$QUNILATOR_HOST" = "you@yourboard.local" ]; then
    QUNILATOR_HOST=
fi

IMAGE=qunibone-crossbuild
PRU_IMAGE=qunibone-pru-cgt

# The PRU code generation tools, pinned to the version that built the firmware
# the emulator has been verified with. clpru's output is what the bus state
# machine's cycle timing depends on, so the compiler is part of the product and
# moving to a newer one is a change to be measured, not a version bump.
PRU_CGT_VERSION=2.3.1

# Build containers write into the mounted tree as this user, so the generated
# firmware and objects are owned by the caller rather than by root. Docker
# Desktop maps bind-mount ownership to the host user on its own; a Linux host
# (a CI runner) does not, and a root-owned tree then breaks the touch and the
# header-stamp write that follow the build.
DOCKER_USER="$(id -u):$(id -g)"

usage() {
    cat <<EOF
usage: $(basename "$0") [-u|-q] [-g] [-d] [-c] [-p] [-t] [-h]

Cross-compile the emulator and its PRU firmware for the BeagleBone in a Docker
container, leaving them in the tree. Without options it builds the optimised
binary for the bus QUNILATOR_BUS names; -d then copies it to the board
build.env names.

  -u  build for UNIBUS for this run, whatever QUNILATOR_BUS says
  -q  build for QBUS for this run, whatever QUNILATOR_BUS says
  -g  build unoptimised and with debug symbols (-O0 -ggdb3), into its own
      object directory 10.03_app_demo/4_deploy<suffix>_dbg
  -d  deploy to the board after a successful build, as QUNILATOR_DEPLOY_MODE
      says: appliance replaces /usr/bin and restarts the service, checkout
      lands the binary in the source tree the board runs from
  -c  remove the object directories first, forcing a full rebuild - and, on a
      UNIBUS build, a full re-run of the CPU core tests
  -p  rebuild the PRU firmware even when it is already present
  -t  skip the CPU core tests of a UNIBUS build
  -h  show this summary (-? does the same)

A UNIBUS build runs the emulated CPU cores against the MAINDEC diagnostics
before it builds, whether the bus came from build.env or from -u.

environment (set in build.env; see build.env.example):
  QUNILATOR_HOST         ssh destination of the board${QUNILATOR_HOST:+ (now $QUNILATOR_HOST)}
  QUNILATOR_BUS          qbus or unibus, the bus that board carries${QUNILATOR_BUS:+ (now $QUNILATOR_BUS)}
  QUNILATOR_DEPLOY_MODE  appliance or checkout${QUNILATOR_DEPLOY_MODE:+ (now $QUNILATOR_DEPLOY_MODE)}
  QUNILATOR_REMOTE_DIR   checkout directory on the board${QUNILATOR_REMOTE_DIR:+ (now $QUNILATOR_REMOTE_DIR)}
EOF
}

# The bus an option asks for, empty when none did: resolved against
# QUNILATOR_BUS once the options are in, so that neither setting has to be
# read before the other.
BUS_OPT=
DEPLOY=0
CLEAN=0
PRU_CLEAN=0
SKIP_TESTS=0
DEBUG=0
# The leading colon silences getopts' own message, so an unknown option is
# reported here instead. "?" is both an option letter and the marker getopts
# uses for a bad one, so the case below asks OPTARG - silent mode sets it to the
# offending letter - which letter it really was.
while getopts ":uqdcpgth" opt; do
    case $opt in
        u) BUS_OPT=unibus;;
        q) BUS_OPT=qbus;;
        g) DEBUG=1;;
        d) DEPLOY=1;;
        c) CLEAN=1;;
        p) PRU_CLEAN=1;;
        t) SKIP_TESTS=1;;
        h) usage; exit 0;;
        ?) case $OPTARG in
               ''|'?') usage; exit 0;;
           esac
           echo "$(basename "$0"): unknown option -$OPTARG" >&2
           usage >&2
           exit 1;;
    esac
done

JOBS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)

# From here on the run is a build, so build.env has to say what it is a build
# for. A first run has no file at all: write it from the example and stop with
# the one instruction that follows.
if [ ! -f build.env ]; then
    cp build.env.example build.env
    echo "build.env did not exist; build.env.example has been copied to it." >&2
    echo "Edit build.env to name your board, then run this again." >&2
    exit 1
fi

missing=
for var in QUNILATOR_HOST QUNILATOR_BUS QUNILATOR_DEPLOY_MODE QUNILATOR_REMOTE_DIR; do
    [ -n "${!var}" ] || missing="$missing $var"
done
if [ -n "$missing" ]; then
    echo "build.env sets no value for:$missing." >&2
    echo "Edit build.env and give each of them one, then run this again." >&2
    exit 1
fi

# Which bus to build for. The board carries one, and build.env is what names
# that board, so the bus belongs there too: a build with no option is the build
# for the board that is going to run it, and -u or -q builds the other one.
#
# The emulator is compiled for its bus, and an appliance deploy installs it as
# /usr/bin/<name> whatever bus it was built for — so a default of "qbus" for a
# board running unibone would replace that binary with one for the wrong bus and
# restart the service onto it. The value is required for exactly that reason.
case "${BUS_OPT:-$QUNILATOR_BUS}" in
    qbus)   SUFFIX=_q; PLATFORM=QBUS ;;
    unibus) SUFFIX=_u; PLATFORM=UNIBUS ;;
    *) echo "QUNILATOR_BUS is \"$QUNILATOR_BUS\"; it is qbus or unibus." \
            "Fix build.env." >&2; exit 1 ;;
esac

# The board's own name: the emulator is installed as /usr/bin/<name> and run by
# <name>.service, so an appliance deploy needs to know which board this is.
. packaging/board.sh

# The one build.env setting that is more than "has a value": the mode names
# what is on the board, and only two boards exist.
case "$QUNILATOR_DEPLOY_MODE" in
    appliance|checkout) ;;
    *) echo "QUNILATOR_DEPLOY_MODE is \"$QUNILATOR_DEPLOY_MODE\";" \
            "it is appliance or checkout. Fix build.env." >&2; exit 1 ;;
esac

# builder image: Debian with the armhf cross toolchain.
#
# The tag carries a hash of the recipe, so editing anything below builds a new
# image instead of reusing one that no longer matches what it says.
CROSSBUILD_RECIPE=$(cat <<'EOF'
# Trixie, the distribution the appliance image carries: the emulator links
# against its shared libraries, so builder and board agree on their versions.
FROM debian:trixie-slim
# armhf as a foreign architecture: the target's libraries are linked into the
# emulator, not run on the builder
# g++ is the native compiler, for the CPU core tests of 10.06_cputest: those run
# on the build machine against a fake bus, so they need a host compiler, not the
# cross one.
RUN dpkg --add-architecture armhf && apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf g++ make file \
        curl ca-certificates bzip2 \
        libx11-dev:armhf libxcb1-dev:armhf libxau-dev:armhf libxdmcp-dev:armhf \
    && rm -rf /var/lib/apt/lists/*
# Sun RPC for the blinkenlight API client: modern glibc no longer bundles it;
# libtirpc replaces it, built without GSSAPI so it links statically
RUN curl -sL https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.4.tar.bz2 | tar xj -C /tmp \
    && cd /tmp/libtirpc-1.3.4 \
    && ./configure --host=arm-linux-gnueabihf --disable-gssapi --disable-shared \
        --prefix=/usr/local/tirpc-armhf \
    && make -j"$(nproc)" && make install \
    && rm -rf /tmp/libtirpc-1.3.4
EOF
)
IMAGE=$IMAGE:$(printf '%s' "$CROSSBUILD_RECIPE" | shasum | cut -c1-12)

if ! docker image inspect $IMAGE >/dev/null 2>&1; then
    echo "Building $IMAGE docker image ..."
    printf '%s\n' "$CROSSBUILD_RECIPE" | docker build -t $IMAGE -
fi

# builder image: the TI PRU code generation tools. clpru is an x86-64 binary
# and its installer is i386, so this image is amd64 whatever the host is, and
# carries the 32-bit C library the installer needs to unpack itself.
if [ $PRU_CLEAN = 1 ] || ! docker image inspect $PRU_IMAGE >/dev/null 2>&1; then
    echo "Building $PRU_IMAGE docker image ..."
    docker build --platform linux/amd64 -t $PRU_IMAGE \
        --build-arg CGT_VERSION=$PRU_CGT_VERSION - <<'EOF'
FROM --platform=linux/amd64 debian:bookworm-slim
ARG CGT_VERSION
RUN dpkg --add-architecture i386 && apt-get update \
    && apt-get install -y --no-install-recommends make curl ca-certificates libc6:i386 \
    && curl -sLo /tmp/cgt.bin \
        "https://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/${CGT_VERSION}/ti_cgt_pru_${CGT_VERSION}_linux_installer_x86.bin" \
    && chmod +x /tmp/cgt.bin \
    && /tmp/cgt.bin --prefix /opt/ti --mode unattended \
    && rm /tmp/cgt.bin && rm -rf /var/lib/apt/lists/*
ENV PRU_CGT=/opt/ti/ti-cgt-pru_${CGT_VERSION}
EOF
fi

# PRU firmware. Both forms are needed - instruction words for the prussdrv
# backend, the ELF itself for remoteproc - and both come out of the same build.
PRU_DEPLOY_DIR=10.01_base/4_deploy$SUFFIX
if [ $PRU_CLEAN = 1 ]; then
    rm -f "$PRU_DEPLOY_DIR"/*.out "$PRU_DEPLOY_DIR"/*_array.c \
          "$PRU_DEPLOY_DIR"/*.object "$PRU_DEPLOY_DIR"/*.pp \
          "$PRU_DEPLOY_DIR"/*.asm "$PRU_DEPLOY_DIR"/*.map "$PRU_DEPLOY_DIR"/*.nfo
    # The internal-bus image is judged stale against its copy in internal/, so
    # that copy goes with the rest: left standing it reads as current, the image
    # is not rebuilt, and the copy the app build links is never put back.
    rm -rf "$PRU_DEPLOY_DIR/internal"
fi
# The firmware is rebuilt when it is missing, and when any PRU source is newer
# than the image built from it. Without the second test a change to the bus
# state machine is compiled into nothing: the app build happily links the image
# already lying here, the board takes a binary whose ARM half has the change
# and whose PRU half does not, and the two disagree in ways that look like a
# hardware fault.
pru_sources_newer() {
    local image=$1
    [ -s "$image" ] || return 0
    [ -n "$(find 10.01_base/2_src/pru0 10.01_base/2_src/pru1${SUFFIX} \
            10.01_base/2_src/shared -newer "$image" -name '*.[ch]' -print -quit \
            2>/dev/null)" ]
}
# The PRU build runs on the container's own filesystem, not on the bind mount.
# clpru is an x86-64 binary emulated on an ARM Mac, and creating its output
# files (.pp, .nfo, .object, interlist .asm) over the virtiofs mount fails
# sporadically - "cannot open preprocessing output file", a different file
# every run. So the sources are copied in, the compiler writes only to /tmp,
# and the finished firmware is copied out after the whole build has succeeded.
# A failed build therefore leaves the previous complete firmware in place -
# there is no partially rebuilt state for the ARM build to pick up. The
# support package and the compiler are read-only inputs and stay where they
# are; reading from the mount has never failed.
pru_make() {
    # $1 = pru source dir under 10.01_base/2_src, $2... = extra make args
    local prudir="$1"; shift
    docker run --rm --platform linux/amd64 --user "$DOCKER_USER" \
        -v "$PWD:/qunibone" \
        -e PRUDIR="$prudir" -e PLATFORM="$PLATFORM" \
        -e DEPLOY_DIR="$PRU_DEPLOY_DIR" $PRU_IMAGE \
        bash -ec '
            cp -a /qunibone/10.01_base/2_src /tmp/src
            make -C "/tmp/src/$PRUDIR" QUNILATOR_DIR=/qunibone \
                QUNILATOR_PLATFORM="$PLATFORM" OBJ_DIR=/tmp/obj "$@"
            mkdir -p "/qunibone/$DEPLOY_DIR"
            cp /tmp/obj/*_code_*.out /tmp/obj/*_code_*.out.map \
               /tmp/obj/*_array.c /tmp/obj/*_array.h "/qunibone/$DEPLOY_DIR/"
        ' pru_make "$@"
}

if [ -z "$(ls "$PRU_DEPLOY_DIR"/*_array.c 2>/dev/null || true)" ] \
        || [ -z "$(ls "$PRU_DEPLOY_DIR"/*.out 2>/dev/null || true)" ] \
        || pru_sources_newer "$(ls "$PRU_DEPLOY_DIR"/pru1_code_*_array.c 2>/dev/null | head -1)"; then
    echo "Building PRU firmware with clpru $PRU_CGT_VERSION ..."
    for prudir in pru0 pru1${SUFFIX}; do
        pru_make "$prudir" all
    done
fi
# The internal-bus PRU1 image: the same sources with NO_PHYSICAL_BUS, compiled
# into their own object directory because the switch reaches every object that
# touches a bus latch. Only the image and its ELF are lifted out; the objects
# stay behind so they never mix with the physical ones.
INT_NAME=$([ "$SUFFIX" = _u ] && echo unibusint || echo qbusint)
# Staleness is judged against the copy in internal/: the lifted-out copies are
# touched after every run for make's sake, which would hide a source edit.
if pru_sources_newer "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}_array.c"; then
    echo "Building the internal-bus PRU firmware ..."
    PRU_DEPLOY_DIR="$PRU_DEPLOY_DIR/internal" pru_make "pru1${SUFFIX}" \
        CC_CODE_FLAGS="-D$PLATFORM -DNO_PHYSICAL_BUS" internal
    cp "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}_array.c" \
       "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}_array.h" \
       "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}.out" "$PRU_DEPLOY_DIR/"
fi

# make must see them as newer than the PRU sources, or it tries to run clpru
touch "$PRU_DEPLOY_DIR"/*_array.c

# The emulated CPU cores against the DEC MAINDEC diagnostics. Host compiler,
# host binary, a bus made of a word array. UNIBUS only: a QBone carries a real
# CPU board and ships no emulated CPU, so the cores are none of its build's
# business. Stamps under 10.06_cputest/4_deploy keep this to the pairs whose
# sources actually changed.
if [ $SKIP_TESTS = 0 ] && [ $PLATFORM = UNIBUS ]; then
    # -c means "build everything again", so it throws away the harness objects
    # and the stamps too and every (core, tape) pair runs afresh. Serially: the
    # clean would otherwise race the compiles of the run that follows.
    if [ $CLEAN = 1 ]; then
        docker run --rm --user "$DOCKER_USER" -v "$PWD:/qunibone" \
            -w /qunibone/10.06_cputest/2_src $IMAGE \
            make QUNIBONE_DIR=/qunibone clean
    fi
    echo "Running the CPU core tests ..."
    docker run --rm --user "$DOCKER_USER" -v "$PWD:/qunibone" \
        -w /qunibone/10.06_cputest/2_src $IMAGE \
        make -j"$JOBS" QUNIBONE_DIR=/qunibone test
fi

# A debug build is a different set of objects from an optimised one, so it gets
# an object directory of its own: the two can then live side by side and neither
# invalidates the other's incremental state. The makefile fixes OBJDIR at
# 4_deploy<suffix>, but a variable given on make's command line wins over the
# makefile's own assignment, so passing it is all that is needed.
if [ $DEBUG = 1 ]; then
    CONFIGURATION=DBG
    OBJDIR="10.03_app_demo/4_deploy${SUFFIX}_dbg"
else
    CONFIGURATION=RELEASE
    OBJDIR="10.03_app_demo/4_deploy$SUFFIX"
fi
HEADER_STAMP="$OBJDIR/.headers.sha"

# Adding or removing a virtual method, or changing a struct layout, in a
# shared header is an ABI change: incremental make relinks stale objects
# compiled against the old layout, and the mismatched vtables crash at
# runtime (a null-vtable jump). The makefile's header dependencies do not
# cover every object, so force a clean build whenever any header under
# 10.01_base/10.02_devices changed since the last build. A content hash is
# used, so re-touching a header without editing it does not trigger a clean.
header_hash() {
    find 10.01_base 10.02_devices -type f \( -name '*.h' -o -name '*.hpp' \) \
        -print0 | sort -z | xargs -0 cat 2>/dev/null | shasum | cut -d' ' -f1
}
HEADER_HASH=$(header_hash)
if [ $CLEAN = 0 ] && [ -f "$HEADER_STAMP" ] \
        && [ "$(cat "$HEADER_STAMP")" != "$HEADER_HASH" ]; then
    echo "Headers under 10.01_base/10.02_devices changed — forcing a clean build (ABI safety)."
    CLEAN=1
fi

if [ $CLEAN = 1 ]; then
    rm -rf "$OBJDIR"
fi

docker run --rm --user "$DOCKER_USER" -v "$PWD:/qunibone" \
    -w /qunibone/10.03_app_demo/2_src $IMAGE \
    make -f makefile$SUFFIX -j"$JOBS" \
        QUNILATOR_DIR=/qunibone \
        OBJDIR="/qunibone/$OBJDIR" \
        MAKE_CONFIGURATION=$CONFIGURATION \
        MAKE_TARGET_ARCH=BBB \
        BBB_CC=arm-linux-gnueabihf-gcc \
        CCDEFS=-I/usr/local/tirpc-armhf/include/tirpc \
        EXTRA_LIBS="-L/usr/local/tirpc-armhf/lib -ltirpc" \
        all

# Two programs come out of the build: qbone-web, the service that serves the web
# interface, and demo, the interactive menu.
BINARY=$OBJDIR/demo
BINARY_WEB=$OBJDIR/qbone-web
file "$BINARY" "$BINARY_WEB"

# record the header state so the next incremental build detects ABI changes
# (the build recreated $OBJDIR); only reached on a successful build (set -e)
echo "$HEADER_HASH" > "$HEADER_STAMP"

# A board flashed from the release image carries no source tree: the package put
# the service at /usr/bin/<name> and a unit of the same name runs it. Upload
# beside it and rename, which replaces the file even while it is running, then
# restart the unit onto the new one.
deploy_appliance() {
    echo "Deploying $BINARY_WEB to $QUNILATOR_HOST:/usr/bin/$NAME ..."
    scp "$BINARY_WEB" "$QUNILATOR_HOST:/tmp/$NAME.new"
    ssh "$QUNILATOR_HOST" "sudo install -m 755 /tmp/$NAME.new /usr/bin/$NAME.new \
        && sudo mv /usr/bin/$NAME.new /usr/bin/$NAME \
        && rm -f /tmp/$NAME.new \
        && sudo systemctl restart $NAME.service"

    # The frontend is served from disk, so swapping it needs no restart. The
    # bundles are content-hashed, so this unpacks over what is there: index.html
    # names the new ones and the superseded ones are simply no longer asked for.
    if [ "$QUNILATOR_DEPLOY_FRONTEND" = 1 ]; then
        echo "Deploying the frontend to $QUNILATOR_HOST:/usr/share/qunilator/frontend ..."
        stage=$(mktemp -d)
        trap 'rm -rf "$stage"' EXIT
        stage_frontend "$stage"
        # --no-xattrs: macOS bsdtar otherwise records a provenance attribute per
        # file, which GNU tar on the board reports as an unknown header for each
        COPYFILE_DISABLE=1 tar --no-xattrs -C "$stage" -czf "$stage.tgz" . \
            2>/dev/null || tar -C "$stage" -czf "$stage.tgz" .
        scp "$stage.tgz" "$QUNILATOR_HOST:/tmp/qunilator-frontend.tgz"
        rm -f "$stage.tgz"
        # --no-same-owner: the archive carries the developer's uid, which means
        # nothing on the board; the web root belongs to root as the package left it
        ssh "$QUNILATOR_HOST" "sudo tar --no-same-owner -C /usr/share/qunilator/frontend \
            -xzf /tmp/qunilator-frontend.tgz && rm -f /tmp/qunilator-frontend.tgz"
    fi
}

# A board with a checkout runs the binary out of it, so the deploy lands in the
# same place the build wrote it.
deploy_checkout() {
    echo "Deploying to $QUNILATOR_HOST:$QUNILATOR_REMOTE_DIR/$BINARY ..."
    # the debug object directory has no counterpart in the checkout on the board
    ssh "$QUNILATOR_HOST" "mkdir -p '$QUNILATOR_REMOTE_DIR/$OBJDIR'"
    # upload beside the binary, then rename: replaces it even while it runs
    scp "$BINARY" "$QUNILATOR_HOST:$QUNILATOR_REMOTE_DIR/$BINARY.new"
    ssh "$QUNILATOR_HOST" "mv '$QUNILATOR_REMOTE_DIR/$BINARY.new' '$QUNILATOR_REMOTE_DIR/$BINARY'"
}

if [ $DEPLOY = 1 ]; then
    case "$QUNILATOR_DEPLOY_MODE" in
        appliance) deploy_appliance;;
        checkout)  deploy_checkout;;
    esac
fi

# The last line says which board this was for. The build takes a minute and
# scrolls past, and the bus now comes from a file rather than the command line,
# so what came out is worth stating rather than inferring from the option that
# was or was not typed.
echo "Built $PLATFORM ($NAME): $BINARY_WEB$([ $DEPLOY = 1 ] \
    && echo " — deployed to $QUNILATOR_HOST")"
