#!/bin/bash
# Cross-compile the demo binary for the BeagleBone in a Docker container.
# A full parallel build takes well under a minute on a desktop, so this is
# the fast path for development; compile.sh on the BeagleBone remains the
# reference build.
#
# The PRU firmware (10.01_base/4_deploy_<suffix>/*_array.c and *.out) is
# generated by the TI clpru compiler, which runs in its own container here, so
# a build needs nothing but this repository and Docker. See PRU_CGT_VERSION
# below for what pins the compiler.
#
# usage:
#   ./crossbuild.sh            build for QBUS (demo binary)
#   ./crossbuild.sh -u         build for UNIBUS
#   ./crossbuild.sh -d         build and deploy to the board build.env names
#   ./crossbuild.sh -c         clean object directory first
#   ./crossbuild.sh -p         rebuild the PRU firmware even if it is present
#
# Both PRU firmwares are built: the one that drives a backplane and the one that
# keeps the bus inside the PRU. The emulator carries both and loads whichever the
# board's bus-mode setting names, so one binary serves either use.
#
# Where -d deploys to is described by build.env, which names one person's board
# and so is not in git. build.env.example documents every setting; copy it and
# fill it in.

set -e
cd "$(dirname "$0")"

# Deploy settings. Sourced whenever the file is there, so a syntax error in it
# is reported by any build rather than only by one that deploys.
if [ -f build.env ]; then
    . ./build.env
fi

IMAGE=qunibone-crossbuild
PRU_IMAGE=qunibone-pru-cgt

# The PRU code generation tools, pinned to the version that built the firmware
# the emulator has been verified with. clpru's output is what the bus state
# machine's cycle timing depends on, so the compiler is part of the product and
# moving to a newer one is a change to be measured, not a version bump.
PRU_CGT_VERSION=2.3.1

# Build containers write into the mounted tree as this user, so the generated
# firmware and objects are owned by the caller rather than by root. Docker
# Desktop maps bind-mount ownership to the host user on its own; a Linux host
# (a CI runner) does not, and a root-owned tree then breaks the touch and the
# header-stamp write that follow the build.
DOCKER_USER="$(id -u):$(id -g)"

SUFFIX=_q
PLATFORM=QBUS
DEPLOY=0
CLEAN=0
PRU_CLEAN=0
while getopts "udcp" opt; do
    case $opt in
        u) SUFFIX=_u; PLATFORM=UNIBUS;;
        d) DEPLOY=1;;
        c) CLEAN=1;;
        p) PRU_CLEAN=1;;
        *) exit 1;;
    esac
done

# The board's own name: the emulator is installed as /usr/bin/<name> and run by
# <name>.service, so an appliance deploy needs to know which board this is.
. packaging/board.sh

# What a deploy needs, checked before the build rather than after it.
if [ $DEPLOY = 1 ]; then
    missing=
    [ -n "$QUNILATOR_HOST" ] || missing="$missing QUNILATOR_HOST"
    case "$QUNILATOR_DEPLOY_MODE" in
        appliance) ;;
        checkout) [ -n "$QUNILATOR_REMOTE_DIR" ] \
                || missing="$missing QUNILATOR_REMOTE_DIR" ;;
        "") missing="$missing QUNILATOR_DEPLOY_MODE" ;;
        *) echo "QUNILATOR_DEPLOY_MODE is \"$QUNILATOR_DEPLOY_MODE\";" \
                "it is appliance or checkout" >&2; exit 1 ;;
    esac
    if [ -n "$missing" ]; then
        echo "-d needs$missing." >&2
        [ -f build.env ] && echo "Set it in build.env." >&2 \
            || echo "Copy build.env.example to build.env and fill it in." >&2
        exit 1
    fi
fi

# builder image: Debian with the armhf cross toolchain.
#
# The tag carries a hash of the recipe, so editing anything below builds a new
# image instead of reusing one that no longer matches what it says.
CROSSBUILD_RECIPE=$(cat <<'EOF'
# Trixie, the distribution the appliance image carries: the emulator links
# against its shared libraries, so builder and board agree on their versions.
FROM debian:trixie-slim
# armhf as a foreign architecture: the target's libraries are linked into the
# emulator, not run on the builder
RUN dpkg --add-architecture armhf && apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf make file \
        curl ca-certificates bzip2 \
        libx11-dev:armhf libxcb1-dev:armhf libxau-dev:armhf libxdmcp-dev:armhf \
    && rm -rf /var/lib/apt/lists/*
# Sun RPC for the blinkenlight API client: modern glibc no longer bundles it;
# libtirpc replaces it, built without GSSAPI so it links statically
RUN curl -sL https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.4.tar.bz2 | tar xj -C /tmp \
    && cd /tmp/libtirpc-1.3.4 \
    && ./configure --host=arm-linux-gnueabihf --disable-gssapi --disable-shared \
        --prefix=/usr/local/tirpc-armhf \
    && make -j"$(nproc)" && make install \
    && rm -rf /tmp/libtirpc-1.3.4
EOF
)
IMAGE=$IMAGE:$(printf '%s' "$CROSSBUILD_RECIPE" | shasum | cut -c1-12)

if ! docker image inspect $IMAGE >/dev/null 2>&1; then
    echo "Building $IMAGE docker image ..."
    printf '%s\n' "$CROSSBUILD_RECIPE" | docker build -t $IMAGE -
fi

# builder image: the TI PRU code generation tools. clpru is an x86-64 binary
# and its installer is i386, so this image is amd64 whatever the host is, and
# carries the 32-bit C library the installer needs to unpack itself.
if [ $PRU_CLEAN = 1 ] || ! docker image inspect $PRU_IMAGE >/dev/null 2>&1; then
    echo "Building $PRU_IMAGE docker image ..."
    docker build --platform linux/amd64 -t $PRU_IMAGE \
        --build-arg CGT_VERSION=$PRU_CGT_VERSION - <<'EOF'
FROM --platform=linux/amd64 debian:bookworm-slim
ARG CGT_VERSION
RUN dpkg --add-architecture i386 && apt-get update \
    && apt-get install -y --no-install-recommends make curl ca-certificates libc6:i386 \
    && curl -sLo /tmp/cgt.bin \
        "https://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/${CGT_VERSION}/ti_cgt_pru_${CGT_VERSION}_linux_installer_x86.bin" \
    && chmod +x /tmp/cgt.bin \
    && /tmp/cgt.bin --prefix /opt/ti --mode unattended \
    && rm /tmp/cgt.bin && rm -rf /var/lib/apt/lists/*
ENV PRU_CGT=/opt/ti/ti-cgt-pru_${CGT_VERSION}
EOF
fi

# PRU firmware. Both forms are needed - instruction words for the prussdrv
# backend, the ELF itself for remoteproc - and both come out of the same build.
PRU_DEPLOY_DIR=10.01_base/4_deploy$SUFFIX
if [ $PRU_CLEAN = 1 ]; then
    rm -f "$PRU_DEPLOY_DIR"/*.out "$PRU_DEPLOY_DIR"/*_array.c \
          "$PRU_DEPLOY_DIR"/*.object "$PRU_DEPLOY_DIR"/*.pp \
          "$PRU_DEPLOY_DIR"/*.asm "$PRU_DEPLOY_DIR"/*.map "$PRU_DEPLOY_DIR"/*.nfo
fi
# The firmware is rebuilt when it is missing, and when any PRU source is newer
# than the image built from it. Without the second test a change to the bus
# state machine is compiled into nothing: the app build happily links the image
# already lying here, the board takes a binary whose ARM half has the change
# and whose PRU half does not, and the two disagree in ways that look like a
# hardware fault.
pru_sources_newer() {
    local image
    image=$(ls "$PRU_DEPLOY_DIR"/pru1_code_*_array.c 2>/dev/null | head -1)
    [ -n "$image" ] || return 0
    [ -n "$(find 10.01_base/2_src/pru0 10.01_base/2_src/pru1${SUFFIX} \
            10.01_base/2_src/shared -newer "$image" -name '*.[ch]' -print -quit \
            2>/dev/null)" ]
}
if [ -z "$(ls "$PRU_DEPLOY_DIR"/*_array.c 2>/dev/null || true)" ] \
        || [ -z "$(ls "$PRU_DEPLOY_DIR"/*.out 2>/dev/null || true)" ] \
        || pru_sources_newer; then
    echo "Building PRU firmware with clpru $PRU_CGT_VERSION ..."
    for prudir in pru0 pru1${SUFFIX}; do
        docker run --rm --platform linux/amd64 --user "$DOCKER_USER" \
            -v "$PWD:/qunibone" \
            -w "/qunibone/10.01_base/2_src/$prudir" $PRU_IMAGE \
            make QUNILATOR_DIR=/qunibone QUNILATOR_PLATFORM=$PLATFORM all
    done
fi
# The internal-bus PRU1 image: the same sources with NO_PHYSICAL_BUS, compiled
# into their own object directory because the switch reaches every object that
# touches a bus latch. Only the image and its ELF are lifted out; the objects
# stay behind so they never mix with the physical ones.
INT_NAME=$([ "$SUFFIX" = _u ] && echo unibusint || echo qbusint)
# Staleness is judged against the copy in internal/: the lifted-out copies are
# touched after every run for make's sake, which would hide a source edit.
if pru_sources_newer "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}_array.c"; then
    echo "Building the internal-bus PRU firmware ..."
    docker run --rm --platform linux/amd64 --user "$DOCKER_USER" \
        -v "$PWD:/qunibone" \
        -w "/qunibone/10.01_base/2_src/pru1${SUFFIX}" $PRU_IMAGE \
        make QUNILATOR_DIR=/qunibone QUNILATOR_PLATFORM=$PLATFORM \
            OBJ_DIR="/qunibone/$PRU_DEPLOY_DIR/internal" \
            CC_CODE_FLAGS="-D$PLATFORM -DNO_PHYSICAL_BUS" internal
    cp "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}_array.c" \
       "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}_array.h" \
       "$PRU_DEPLOY_DIR/internal/pru1_code_${INT_NAME}.out" "$PRU_DEPLOY_DIR/"
fi

# make must see them as newer than the PRU sources, or it tries to run clpru
touch "$PRU_DEPLOY_DIR"/*_array.c

OBJDIR="10.03_app_demo/4_deploy$SUFFIX"
HEADER_STAMP="$OBJDIR/.headers.sha"

# Adding or removing a virtual method, or changing a struct layout, in a
# shared header is an ABI change: incremental make relinks stale objects
# compiled against the old layout, and the mismatched vtables crash at
# runtime (a null-vtable jump). The makefile's header dependencies do not
# cover every object, so force a clean build whenever any header under
# 10.01_base/10.02_devices changed since the last build. A content hash is
# used, so re-touching a header without editing it does not trigger a clean.
header_hash() {
    find 10.01_base 10.02_devices -type f \( -name '*.h' -o -name '*.hpp' \) \
        -print0 | sort -z | xargs -0 cat 2>/dev/null | shasum | cut -d' ' -f1
}
HEADER_HASH=$(header_hash)
if [ $CLEAN = 0 ] && [ -f "$HEADER_STAMP" ] \
        && [ "$(cat "$HEADER_STAMP")" != "$HEADER_HASH" ]; then
    echo "Headers under 10.01_base/10.02_devices changed — forcing a clean build (ABI safety)."
    CLEAN=1
fi

if [ $CLEAN = 1 ]; then
    rm -rf "$OBJDIR"
fi

docker run --rm --user "$DOCKER_USER" -v "$PWD:/qunibone" \
    -w /qunibone/10.03_app_demo/2_src $IMAGE \
    make -f makefile$SUFFIX -j"$(sysctl -n hw.ncpu 2>/dev/null || echo 4)" \
        QUNILATOR_DIR=/qunibone \
        MAKE_CONFIGURATION=RELEASE \
        MAKE_TARGET_ARCH=BBB \
        BBB_CC=arm-linux-gnueabihf-gcc \
        CCDEFS=-I/usr/local/tirpc-armhf/include/tirpc \
        EXTRA_LIBS="-L/usr/local/tirpc-armhf/lib -ltirpc" \
        all

# Two programs come out of the build: qbone-web, the service that serves the web
# interface, and demo, the interactive menu.
BINARY=$OBJDIR/demo
BINARY_WEB=$OBJDIR/qbone-web
file "$BINARY" "$BINARY_WEB"

# record the header state so the next incremental build detects ABI changes
# (the build recreated $OBJDIR); only reached on a successful build (set -e)
echo "$HEADER_HASH" > "$HEADER_STAMP"

# A board flashed from the release image carries no source tree: the package put
# the service at /usr/bin/<name> and a unit of the same name runs it. Upload
# beside it and rename, which replaces the file even while it is running, then
# restart the unit onto the new one.
deploy_appliance() {
    echo "Deploying $BINARY_WEB to $QUNILATOR_HOST:/usr/bin/$NAME ..."
    scp "$BINARY_WEB" "$QUNILATOR_HOST:/tmp/$NAME.new"
    ssh "$QUNILATOR_HOST" "sudo install -m 755 /tmp/$NAME.new /usr/bin/$NAME.new \
        && sudo mv /usr/bin/$NAME.new /usr/bin/$NAME \
        && rm -f /tmp/$NAME.new \
        && sudo systemctl restart $NAME.service"

    # The frontend is served from disk, so swapping it needs no restart. The
    # bundles are content-hashed, so this unpacks over what is there: index.html
    # names the new ones and the superseded ones are simply no longer asked for.
    if [ "$QUNILATOR_DEPLOY_FRONTEND" = 1 ]; then
        echo "Deploying the frontend to $QUNILATOR_HOST:/usr/share/qunilator/frontend ..."
        stage=$(mktemp -d)
        trap 'rm -rf "$stage"' EXIT
        stage_frontend "$stage"
        # --no-xattrs: macOS bsdtar otherwise records a provenance attribute per
        # file, which GNU tar on the board reports as an unknown header for each
        COPYFILE_DISABLE=1 tar --no-xattrs -C "$stage" -czf "$stage.tgz" . \
            2>/dev/null || tar -C "$stage" -czf "$stage.tgz" .
        scp "$stage.tgz" "$QUNILATOR_HOST:/tmp/qunilator-frontend.tgz"
        rm -f "$stage.tgz"
        # --no-same-owner: the archive carries the developer's uid, which means
        # nothing on the board; the web root belongs to root as the package left it
        ssh "$QUNILATOR_HOST" "sudo tar --no-same-owner -C /usr/share/qunilator/frontend \
            -xzf /tmp/qunilator-frontend.tgz && rm -f /tmp/qunilator-frontend.tgz"
    fi
}

# A board with a checkout runs the binary out of it, so the deploy lands in the
# same place the build wrote it.
deploy_checkout() {
    echo "Deploying to $QUNILATOR_HOST:$QUNILATOR_REMOTE_DIR/$BINARY ..."
    scp "$BINARY" "$QUNILATOR_HOST:$QUNILATOR_REMOTE_DIR/$BINARY.new"
    ssh "$QUNILATOR_HOST" "mv '$QUNILATOR_REMOTE_DIR/$BINARY.new' '$QUNILATOR_REMOTE_DIR/$BINARY'"
}

if [ $DEPLOY = 1 ]; then
    case "$QUNILATOR_DEPLOY_MODE" in
        appliance) deploy_appliance;;
        checkout)  deploy_checkout;;
    esac
fi
