/* pru.cpp: Management interface to PRU0 & PRU1.

 Copyright (c) 2018, Joerg Hoppe
 j_hoppe@t-online.de, www.retrocmp.com

 Permission is hereby granted, free of charge, to any person obtaining a
 copy of this software and associated documentation files (the "Software"),
 to deal in the Software without restriction, including without limitation
 the rights to use, copy, modify, merge, publish, distribute, sublicense,
 and/or sell copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 JOERG HOPPE BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


 12-nov-2018  JH      entered beta phase

 Management interface to PRU0 & 1:
 - setup interrupt
 - download code from arrays in pru0/1_config.c

 Partly copyright (c) 2014 dhenke@mythopoeic.org

 PRU progam code:
 For different QUniBone operation modes special program code is used for PRU0 and PRU1 each.
 One single omnipotent program code can not be used due to 2K code space limit.
 ARM code asu to reload appropriate PRU program code according to current function
 (PRU selftest, QBUS/UNIBUS slave, QBUS/UNIBUS master, logic analyzer, etc.)


 ***/
#define _PRU_CPP_

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include <assert.h>

#include <fcntl.h>

#include "utils.hpp"
#include "logger.hpp"
#include "pru_backend.hpp"
#include "pruss_intc_mapping.h"
#include "mailbox.h"
#include "ddrmem.h"
#include "iopageregister.h"

#include "pru.hpp"

/*** PRU code arrays generated by clpru / hexpru  ***
 Program code is generated by "lcpru" and "hexpru --array" as C-array source code.

 These arrays are included here and wrapped for use by ARM/C++ classes.

 Format:
 const uint32_t target_image_0[] = {
 0x240000c0,
 ..
 0x20c30000};

 const uint8_t target_image_1[] = {
 0x01,
 ...
 0x00};
 */
//  under c++ linker error with const attribute ?!
#define const
#include "pru0_code_all_array.c"
// the same firmware as an ELF file, for the backend that loads one
#include "pru0_code_all_elf.c"
#include "pru1_code_test_array.c"
#include "pru1_code_test_elf.c"
#if defined(UNIBUS)
#include "pru1_code_unibus_array.c"
#include "pru1_code_unibus_elf.c"
// the same firmware with the bus kept inside the PRU, for a board that is a
// machine by itself rather than a card in someone else's backplane
#include "pru1_code_unibusint_array.c"
#include "pru1_code_unibusint_elf.c"
#elif defined(QBUS)
#include "pru1_code_qbus_array.c"
#include "pru1_code_qbus_elf.c"
#include "pru1_code_qbusint_array.c"
#include "pru1_code_qbusint_elf.c"
#endif
#undef const

// Singleton
pru_c *pru;

pru_c::pru_c() 
{
	prucode_id = PRUCODE_NONE;
	log_label = "PRU";
}

/*** pru_setup() -- initialize PRU and interrupt handler

 Initializes both PRUs and sets up PRU_EVTOUT_0 handler.

 The argument is a pointer to a null-terminated string containing the path
 to the file containing the PRU program binary.

 Returns 0 on success, non-0 on error.
 ***/

// entry for one program code variant for both PRUs
struct prucode_entry {
	unsigned id;
	// ptr to PRU0 code array generated by clpru
	uint32_t *pru0_code_array;
	unsigned pru0_code_array_sizeof;
	uint32_t pru0_entry;
	// the same firmware as an ELF, which remoteproc loads instead
	const uint8_t *pru0_elf;
	unsigned pru0_elf_size;
	// smame for PRU1
	uint32_t *pru1_code_array;
	unsigned pru1_code_array_sizeof;
	uint32_t pru1_entry;
	const uint8_t *pru1_elf;
	unsigned pru1_elf_size;
	// properties required for certain functions
};

// local static dictionary of program code variants
struct prucode_entry prucode[] = {
// self test functions
		{ pru_c::PRUCODE_TEST, //
				pru0_code_all_image_0, sizeof(pru0_code_all_image_0), PRU0_ENTRY_ADDR, //
				pru0_code_all_elf, sizeof(pru0_code_all_elf), //
				pru1_code_test_image_0, sizeof(pru1_code_test_image_0), PRU1_ENTRY_ADDR, //
				pru1_code_test_elf, sizeof(pru1_code_test_elf) //
		},//
		  // full bus protocols for QBUS/UNIBUS device emulation
		{ pru_c::PRUCODE_EMULATION, //
				pru0_code_all_image_0, sizeof(pru0_code_all_image_0), PRU0_ENTRY_ADDR, //
				pru0_code_all_elf, sizeof(pru0_code_all_elf), //
#if defined(UNIBUS)				
		pru1_code_unibus_image_0, sizeof(pru1_code_unibus_image_0), PRU1_ENTRY_ADDR, //
		pru1_code_unibus_elf, sizeof(pru1_code_unibus_elf) //
#elif defined(QBUS)				
		pru1_code_qbus_image_0, sizeof(pru1_code_qbus_image_0), PRU1_ENTRY_ADDR, //
		pru1_code_qbus_elf, sizeof(pru1_code_qbus_elf) //
#endif		
	}, //
	  // the same emulation with an internal bus: the latches stay in the PRU
	  // and read back what was written, so the board answers its own cycles
	  // instead of driving a backplane
		{ pru_c::PRUCODE_EMULATION_INTERNAL_BUS, //
				pru0_code_all_image_0, sizeof(pru0_code_all_image_0), PRU0_ENTRY_ADDR, //
				pru0_code_all_elf, sizeof(pru0_code_all_elf), //
#if defined(UNIBUS)
		pru1_code_unibusint_image_0, sizeof(pru1_code_unibusint_image_0), PRU1_ENTRY_ADDR, //
		pru1_code_unibusint_elf, sizeof(pru1_code_unibusint_elf) //
#elif defined(QBUS)
		pru1_code_qbusint_image_0, sizeof(pru1_code_qbusint_image_0), PRU1_ENTRY_ADDR, //
		pru1_code_qbusint_elf, sizeof(pru1_code_qbusint_elf) //
#endif
	}, //
	   // end marker
	{ pru_c::PRUCODE_EOD, NULL, 0, 0, NULL, 0, 0, 0, 0, NULL, 0 } };

int pru_c::start(enum prucode_enum _prucode_id) 
{
	timeout_c timeout;
	int rtn;

	// use stop() before restart()
	assert(this->prucode_id == PRUCODE_NONE);

	/* claim the PRU subsystem through whichever interface the kernel offers */
	if (!pru_backend_select()) {
		ERROR("no way to reach the PRUs: neither uio_pruss nor remoteproc");
		rtn = -1;
		goto error;
	}
	INFO("PRUs reached through %s", pru_backend->name());

	/*
	 http://credentiality2.blogspot.com/2015/09/beaglebone-pru-ddr-memory-access.html
	 * get pointer to shared DDR
	 */
	// The host memory the PRUs use as the emulated machine's memory.
	{
		void *virt = NULL;
		size_t len = 0;
		uint32_t phys = 0;
		if (!pru_backend->map_host_memory(&virt, &len, &phys)) {
			rtn = -1;
			goto error;
		}
		ddrmem->base_virtual = (ddrmem_t *) virt;
		ddrmem->len = len;
		ddrmem->base_physical = phys;

		// The range is reserved physical memory and keeps whatever the last
		// program left in it, so the adapter's map is switched off and emptied
		// here. A machine without an adapter must find it off, and one with an
		// adapter fills it in for itself.
		ddrmem->base_virtual->unibus_map_active = 0;
		memset((void *) ddrmem->base_virtual->unibus_map, 0,
				sizeof(ddrmem->base_virtual->unibus_map));
	}
	ddrmem->info(); // may abort program

	// get address of mail box struct in PRU
	mailbox_connect();
	// now all mailbox command fields initialized/cleared, PRUs can be started

	// get address of device register descriptor struct in PRU
	iopageregisters_connect();

	// search code in dictionary
	struct prucode_entry *pce;
	for (pce = prucode; pce->id != _prucode_id && pce->id != PRUCODE_EOD; pce++)
		;
	if (pce->id == PRUCODE_EOD)
		FATAL("PRU program code for config %u not found", pce->id);

	/* load code from arrays PRU*_code[] into PRU and start at 0
	 */
	if (pce->pru0_code_array_sizeof > PRUSS_MAX_IRAM_SIZE) {
		FATAL("PRU0 code too large. Closing program");
	}
	if (!pru_backend->load_and_start(0, pce->pru0_code_array, pce->pru0_code_array_sizeof,
			pce->pru0_elf, pce->pru0_elf_size, pce->pru0_entry)) {
		FATAL("could not start PRU0");
		goto error;
	}

	if (pce->pru1_code_array_sizeof > PRUSS_MAX_IRAM_SIZE) {
		FATAL("PRU1 code too large.");
	}
	if (!pru_backend->load_and_start(1, pce->pru1_code_array, pce->pru1_code_array_sizeof,
			pce->pru1_elf, pce->pru1_elf_size, pce->pru1_entry)) {
		FATAL("could not start PRU1");
	}
	INFO("Loaded and started PRU code with id = %d", _prucode_id);

	timeout.wait_ms(100); // wait for PRU to come up, much too long

	prucode_id = _prucode_id;

	// verify PRU1 is executing its command loop
	mailbox->arm2pru_req = ARM2PRU_NOP;
	timeout.wait_ms(1);
	if (mailbox->arm2pru_req != ARM2PRU_NONE) {
		FATAL("PRU1 is not executing its command loop");
		goto error;
	}

	return rtn;

	error: //
	pru->stop();
	FATAL("Could not connect to PRU.\n"
			"- Correct Device Tree Overlay loaded?\n"
			"- Check also /sys/class/uio/uio*.");
	return rtn; // not reached
}

/***  pru_c::stop() -- halt PRU and release driver

 Halts both PRUs and releases the interface they were reached through.

 Returns 0 on success, non-0 on error.
 ***/
int pru_c::stop(void) 
{
	int rtn = 0;
	prucode_id = PRUCODE_NONE;

	if (pru_backend == NULL)
		return rtn; // never started

	pru_backend->clear_event();
	pru_backend->halt(0);
	pru_backend->halt(1);
	pru_backend->close();

	return rtn;
}

