/*
 * DDR memory structures common to ARM and PRU
 * Only used for memory emulation, PRU read access to ARM DDR maybe upto 400ns !
 */

#ifndef _DDRMEM_H_
#define _DDRMEM_H_

#include <stdint.h>

#include "qunibus.h"

/***** start of shared structs *****/
// on PRU. all struct are byte-packed, no "#pragma pack" there
// (support answer 20.5.2018,  issue CODEGEN-4832)
#ifdef ARM
#pragma pack(push,1)
#endif

// A UNIBUS adapter's map register file, as the DW780 of a VAX-11/780 has it:
// one register per 512 byte page of the eighteen bit address space. A device
// drives an eighteen bit address, the register indexed by its page supplies
// the page frame the transfer really reaches, and the offset within the page
// carries over. The layout is the adapter's, so a register is valid only with
// its top bit set - see UNIBUS_MAP_VALID.
#define UNIBUS_MAP_REGISTERS	496		// pages of the 18 bit space that map
#define UNIBUS_MAP_PAGE_SHIFT	9		// 512 bytes to a page
#define UNIBUS_MAP_VALID	0x80000000	// register is allocated
#define UNIBUS_MAP_BYTE_OFFSET	0x40000000	// transfer moves up one byte
#define UNIBUS_MAP_DATA_PATH	0x0e000000	// buffered data path number
#define UNIBUS_MAP_FRAME	0x001fffff	// page frame of the answer

typedef struct {
	// DDR mem is only used to emulate QBUS/UNIBUS memory
	// This slow DDR RAM is not used otherwise
	qunibus_memory_t memory;

	// The map registers a processor behind a UNIBUS adapter puts between a
	// device's address and its own memory. Empty, and the PRU translates
	// nothing: a device's address is the address memory answers at, which is
	// what a PDP-11 has. The ARM fills it in for a machine that has an adapter.
	uint32_t unibus_map[UNIBUS_MAP_REGISTERS];

	// Whether the map above is to be applied at all. Kept beside it so the PRU
	// reads one word to find out, rather than scanning the file.
	uint32_t unibus_map_active;
} ddrmem_t;

#ifdef ARM
#pragma pack(pop)
#endif
/***** end of shared structs *****/

#ifdef ARM
// included by ARM code

#include "logsource.hpp"

class ddrmem_c: public logsource_c {
public:
	/* these values are generated by prussdrv functions */
	// base address of shared DDR memory, in ARM Linux memory space
	volatile ddrmem_t *base_virtual;
	uint32_t len;	// size of allocated range as given by UIO driver
	// physical ddrmem_base address, for access by PRU
	uint32_t base_physical;

	// emulated address range
	bool enabled = false; // true if startaddr <= endaddr
	uint32_t qunibus_startaddr;
	uint32_t qunibus_endaddr; 

	uint32_t pmi_address_overlay ;

	ddrmem_c();
	void info(void);
	void save(char *fname);
	void load(char *fname);
	void clear(void);
	void fill_pattern(void);
	void fill_pattern_pru(void);
	void unibus_slave(uint32_t startaddr, uint32_t endaddr);
	bool set_range(uint32_t startaddr, 	uint32_t endaddr);
	bool deposit(uint32_t addr, uint16_t w);
	bool exam(uint32_t addr, uint16_t *w);

	bool pmi_deposit(uint32_t addr, uint16_t w);
	bool pmi_exam(uint32_t addr, uint16_t *w);
	void set_pmi_address_overlay(uint32_t address_overlay) ;
		
	bool iopage_deposit(uint32_t addr, uint16_t w) ;
	bool iopage_exam(uint32_t addr, uint16_t *w) ;
	
};

#ifndef _DDRMEM_C_
// base address of shared DDR memory, in ARM Linux memory space
extern ddrmem_c *ddrmem;
#endif

#else
// included by PRU code
// set a word in simulated memory
#define DDRMEM_MEMSET_W(addr,dataw) \
    	( mailbox.ddrmem_base_physical->memory.words[(addr)/2] = (dataw) )
// set a byte in simulated memory
#define DDRMEM_MEMSET_B(addr,datab) \
    	( mailbox.ddrmem_base_physical->memory.bytes[(addr)] = (datab) )

// return a word from simulated memory
#define DDRMEM_MEMGET_W(addr) \
    	( mailbox.ddrmem_base_physical->memory.words[(addr)/2] )

void ddrmem_fill_pattern(void);

#endif

#endif
